/// Flutter icons MyIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData wallet = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData attach_money = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData money_off = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bank = const IconData(0xf19c, fontFamily: _kFontFam);
  static const IconData cc_mastercard = const IconData(0xf1f1, fontFamily: _kFontFam);
}
